In [1]:
%matplotlib inline

import warnings; warnings.simplefilter('ignore')

In [99]:
import pandas as pd
import os
from functools import reduce
import matplotlib.pyplot as plt
inline_rc = dict(plt.rcParams)
import numpy as np

from scipy.stats.stats import pearsonr
from scipy import stats
from scipy.stats import ks_2samp
from scipy.stats import entropy
from scipy.stats import norm
from scipy.stats import lognorm
from scipy.stats import nbinom
from scipy.stats.mstats import gmean
from scipy.cluster import hierarchy
from scipy.cluster.hierarchy import average
from scipy.cluster.hierarchy import dendrogram


import statsmodels.api as sm
lowess = sm.nonparametric.lowess
import math

import scipy.spatial.distance
from scipy.spatial.distance import *

import scipy.cluster

import sklearn
import sklearn.preprocessing

from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.manifold import TSNE

from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from matplotlib.colors import LinearSegmentedColormap

import seaborn as sns

from PIL import Image

In [21]:
from scipy import ndimage
from scipy import misc

import collections
from collections import Counter

In [12]:
pancan = pd.read_csv("data/pancan/data.csv")
pancan = pancan.set_indexdex("sample")

gene_0    gene_1    gene_2     gene_3     gene_4  gene_5  \
sample                                                                   
sample_0    0.000000  2.017209  3.265527   5.478487  10.431999     0.0   
sample_1    0.000000  0.592732  1.588421   7.586157   9.623011     0.0   
sample_2    0.000000  3.511759  4.327199   6.881787   9.870730     0.0   
sample_3    0.000000  3.663618  4.507649   6.659068  10.196184     0.0   
sample_4    0.000000  2.655741  2.821547   6.539454   9.738265     0.0   
sample_5    0.000000  3.467853  3.581918   6.620243   9.706829     0.0   
sample_6    0.000000  1.224966  1.691177   6.572007   9.640511     0.0   
sample_7    0.000000  2.854853  1.750478   7.226720   9.758691     0.0   
sample_8    0.000000  3.992125  2.772730   6.546692  10.488252     0.0   
sample_9    0.000000  3.642494  4.423558   6.849511   9.464466     0.0   
sample_10   0.000000  3.492071  3.553373   7.151707  10.253446     0.0   
sample_11   0.000000  2.941181  2.663276   6.561690   9.376293     0.0   
sample_12   0.000000  3.970348  2.364292   7.145443   9.240605     0.0   
sample_13   0.000000  1.551048  3.529846   6.326825  10.633849     0.0   
sample_14   0.000000  1.964842  2.183010   6.596832  10.248141     0.0   
sample_15   0.000000  2.901379  3.685368   6.669665   9.999098     0.0   
sample_16   0.000000  3.460913  3.618474   5.661048   9.731217     0.0   
sample_17   0.000000  3.004519  3.007178   6.524205   9.062661     0.0   
sample_18   0.000000  1.541465  2.541540   6.843255   9.444468     0.0   
sample_19   0.000000  4.167583  3.841389   6.976123   9.982252     0.0   
sample_20   0.000000  2.066916  2.619953   6.757997  11.123940     0.0   
sample_21   0.000000  3.529783  2.976712   6.038416   9.437973     0.0   
sample_22   0.000000  1.131853  2.351515   6.845841   9.196860     0.0   
sample_23   0.000000  3.121844  2.473943   7.119616  10.732490     0.0   
sample_24   0.000000  4.801852  2.648465   6.009255   9.611917     0.0   
sample_25   0.341758  4.317702  3.642678   6.790003   8.435999     0.0   
sample_26   0.000000  2.325242  3.247092   8.174007  10.065053     0.0   
sample_27   0.000000  0.657091  1.026304   5.411196   9.601388     0.0   
sample_28   0.000000  3.670081  3.382792   7.581939   9.386658     0.0   
sample_29   0.000000  5.688295  4.899949  10.129528  10.093695     0.0   
...              ...       ...       ...        ...        ...     ...   
sample_771  0.000000  3.683427  4.158555   5.976767  10.272548     0.0   
sample_772  0.000000  2.566888  2.370583   6.459294   9.874400     0.0   
sample_773  0.000000  3.280006  3.607425   5.659805  10.064864     0.0   
sample_774  0.000000  2.542852  2.020235   5.083098  10.328428     0.0   
sample_775  0.000000  1.584337  2.610629   6.813538   9.368515     0.0   
sample_776  0.000000  0.000000  2.316406   6.510695   9.932385     0.0   
sample_777  0.000000  0.792022  2.542010   6.286147   9.183747     0.0   
sample_778  0.000000  3.834731  1.894372   6.314852  10.964370     0.0   
sample_779  0.000000  3.482255  3.064952   6.699288  10.134182     0.0   
sample_780  0.000000  1.693944  2.605139   6.487568   9.533067     0.0   
sample_781  0.000000  1.499527  3.213254   6.873949   9.091655     0.0   
sample_782  0.000000  3.031942  2.575554   6.403079  10.485024     0.0   
sample_783  0.000000  2.060705  3.719830   6.427137  10.432187     0.0   
sample_784  0.000000  2.656016  1.746958   6.641060  10.519164     0.0   
sample_785  0.000000  2.752963  1.960549   5.748145  10.248912     0.0   
sample_786  0.000000  2.364460  3.180689   6.745049   9.499661     0.0   
sample_787  0.000000  4.315436  4.398385   6.273313  10.346890     0.0   
sample_788  0.000000  4.869200  4.087717   6.369039   9.684507     0.0   
sample_789  0.000000  1.687061  2.826376   5.830164  10.921023     0.0   
sample_790  0.000000  2.301734  1.814550   7.013462   9.750047     0.0   
sample_791  0.000000  3.080061  2.815739   6.209617   9.644469     0.0   
sample_792  0.0000

In [16]:
pancanl = pd.read_csv("data/pancan/labels.csv")
pancanl = pancanl.set_index("sample")

In [17]:
pancanl['Class'].unique()

array(['PRAD', 'LUAD', 'BRCA', 'KIRC', 'COAD'], dtype=object)

In [92]:
pancanld = dict((v,i) for (i, v) in enumerate(pancanl['Class'].unique()))

In [93]:
pancanld

{'BRCA': 2, 'COAD': 4, 'KIRC': 3, 'LUAD': 1, 'PRAD': 0}

In [14]:
km = KMeans(n_clusters = 5, init = 'k-means++')
km.fit(pancan)
pc_km = km.fit_predict(pancan)

In [15]:
pc_km

array([1, 2, 1, 1, 0, 1, 3, 1, 0, 1, 0, 3, 1, 0, 0, 0, 2, 3, 3, 1, 0, 3, 2,
       0, 3, 2, 4, 0, 0, 0, 0, 0, 3, 0, 1, 0, 3, 2, 0, 0, 3, 1, 1, 3, 3, 0,
       1, 4, 0, 2, 0, 2, 0, 1, 4, 0, 0, 4, 3, 0, 2, 0, 0, 2, 1, 4, 0, 1, 3,
       0, 3, 0, 0, 2, 0, 2, 0, 3, 1, 4, 0, 1, 0, 0, 1, 1, 0, 0, 3, 0, 1, 1,
       0, 0, 0, 1, 4, 0, 1, 0, 0, 3, 0, 3, 2, 3, 2, 4, 2, 2, 1, 0, 2, 1, 0,
       3, 3, 3, 0, 0, 2, 3, 2, 0, 1, 1, 1, 0, 3, 0, 4, 0, 4, 0, 0, 3, 2, 0,
       3, 4, 0, 1, 0, 3, 2, 4, 1, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 1, 1, 2, 1,
       2, 3, 0, 1, 2, 4, 3, 2, 0, 3, 2, 0, 2, 0, 0, 0, 1, 0, 3, 4, 3, 0, 1,
       1, 1, 2, 2, 0, 2, 2, 3, 2, 1, 2, 0, 0, 0, 2, 2, 0, 3, 3, 3, 3, 1, 0,
       1, 0, 2, 2, 0, 1, 0, 1, 0, 0, 0, 2, 0, 3, 2, 3, 3, 2, 0, 3, 1, 0, 2,
       2, 1, 4, 0, 3, 1, 3, 4, 0, 3, 3, 2, 1, 1, 2, 2, 3, 0, 0, 4, 0, 1, 4,
       0, 1, 3, 1, 1, 1, 0, 4, 4, 2, 4, 4, 1, 2, 0, 0, 3, 3, 0, 4, 1, 3, 1,
       0, 0, 3, 0, 0, 0, 0, 2, 2, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 3, 0, 0, 2,
       1, 0,

In [18]:
labels = pancanl.Class.values

In [19]:
labels

array(['PRAD', 'LUAD', 'PRAD', 'PRAD', 'BRCA', 'PRAD', 'KIRC', 'PRAD',
       'BRCA', 'PRAD', 'BRCA', 'KIRC', 'PRAD', 'BRCA', 'BRCA', 'BRCA',
       'LUAD', 'KIRC', 'KIRC', 'PRAD', 'BRCA', 'KIRC', 'LUAD', 'BRCA',
       'KIRC', 'LUAD', 'COAD', 'BRCA', 'BRCA', 'BRCA', 'BRCA', 'BRCA',
       'KIRC', 'BRCA', 'PRAD', 'BRCA', 'KIRC', 'LUAD', 'BRCA', 'BRCA',
       'KIRC', 'PRAD', 'PRAD', 'KIRC', 'KIRC', 'BRCA', 'PRAD', 'COAD',
       'BRCA', 'LUAD', 'BRCA', 'LUAD', 'BRCA', 'PRAD', 'COAD', 'BRCA',
       'BRCA', 'COAD', 'KIRC', 'BRCA', 'LUAD', 'KIRC', 'BRCA', 'LUAD',
       'PRAD', 'COAD', 'BRCA', 'PRAD', 'KIRC', 'BRCA', 'KIRC', 'BRCA',
       'BRCA', 'LUAD', 'BRCA', 'LUAD', 'BRCA', 'KIRC', 'PRAD', 'COAD',
       'BRCA', 'PRAD', 'BRCA', 'BRCA', 'PRAD', 'PRAD', 'BRCA', 'BRCA',
       'KIRC', 'BRCA', 'PRAD', 'PRAD', 'BRCA', 'BRCA', 'BRCA', 'PRAD',
       'COAD', 'BRCA', 'PRAD', 'BRCA', 'BRCA', 'KIRC', 'BRCA', 'KIRC',
       'LUAD', 'KIRC', 'LUAD', 'COAD', 'LUAD', 'LUAD', 'PRAD', 'BRCA',
      

In [95]:
labelsi = [pancanld[x] for x in labels]

In [96]:
labelsi

[0,
 1,
 0,
 0,
 2,
 0,
 3,
 0,
 2,
 0,
 2,
 3,
 0,
 2,
 2,
 2,
 1,
 3,
 3,
 0,
 2,
 3,
 1,
 2,
 3,
 1,
 4,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 0,
 2,
 3,
 1,
 2,
 2,
 3,
 0,
 0,
 3,
 3,
 2,
 0,
 4,
 2,
 1,
 2,
 1,
 2,
 0,
 4,
 2,
 2,
 4,
 3,
 2,
 1,
 3,
 2,
 1,
 0,
 4,
 2,
 0,
 3,
 2,
 3,
 2,
 2,
 1,
 2,
 1,
 2,
 3,
 0,
 4,
 2,
 0,
 2,
 2,
 0,
 0,
 2,
 2,
 3,
 2,
 0,
 0,
 2,
 2,
 2,
 0,
 4,
 2,
 0,
 2,
 2,
 3,
 2,
 3,
 1,
 3,
 1,
 4,
 1,
 1,
 0,
 2,
 1,
 0,
 2,
 3,
 3,
 3,
 2,
 2,
 1,
 3,
 1,
 2,
 0,
 0,
 0,
 2,
 3,
 1,
 4,
 2,
 4,
 2,
 2,
 3,
 1,
 2,
 3,
 4,
 2,
 0,
 2,
 3,
 1,
 4,
 0,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 0,
 0,
 1,
 0,
 1,
 3,
 2,
 0,
 1,
 4,
 3,
 1,
 2,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 3,
 4,
 3,
 2,
 0,
 0,
 0,
 1,
 1,
 2,
 1,
 1,
 3,
 1,
 0,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 3,
 3,
 3,
 3,
 0,
 2,
 0,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 1,
 2,
 3,
 1,
 3,
 3,
 1,
 2,
 3,
 0,
 2,
 1,
 1,
 0,
 4,
 2,
 3,
 0,
 3,
 4,
 2,
 3,
 3,
 1,
 0,
 0,
 1,
 1,
 3,
 2,
 2,
 4,


In [22]:
for c in [0,1,2,3,4]:
    print (c,Counter()

Counter({'BRCA': 300, 'COAD': 78, 'KIRC': 146, 'LUAD': 141, 'PRAD': 136})

In [27]:
labels[pc_km == 4]

array(['COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD',
       'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD',
       'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD',
       'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD',
       'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD',
       'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD',
       'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD',
       'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD',
       'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD', 'COAD',
       'COAD', 'COAD', 'COAD', 'COAD', 'COAD'], dtype=object)

In [97]:
X = pancan.values
y = np.array(labelsi)

In [86]:
n = 50
Xs = X[:,np.random.choice(range(0,X.shape[1]),n,replace=False)]

In [87]:
km = KMeans(n_clusters = 5, init = 'k-means++')
km.fit(Xs)
pc_km = km.fit_predict(Xs)

In [88]:
for i in [0,1,2,3,4]:
    print (i,Counter(labels[pc_km == i]))

0 Counter({'KIRC': 114, 'LUAD': 10, 'BRCA': 5, 'COAD': 1})
1 Counter({'PRAD': 131, 'BRCA': 2})
2 Counter({'BRCA': 270, 'PRAD': 5, 'LUAD': 5, 'KIRC': 4, 'COAD': 1})
3 Counter({'LUAD': 114, 'KIRC': 27, 'BRCA': 13})
4 Counter({'COAD': 76, 'LUAD': 12, 'BRCA': 10, 'KIRC': 1})


In [104]:
X_tr, X_te, y_tr, y_te = model_selection.train_test_split(X, y, test_size=.2)

In [105]:
# Make predictions on validation dataset
knn = KNeighborsClassifier()
knn.fit(X_tr, y_tr)
predictions = knn.predict(X_te)
print(accuracy_score(y_te, predictions))
print(confusion_matrix(y_te, predictions))
print(classification_report(y_te, predictions))

1.0
[[32  0  0  0  0]
 [ 0 32  0  0  0]
 [ 0  0 52  0  0]
 [ 0  0  0 34  0]
 [ 0  0  0  0 11]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        32
          1       1.00      1.00      1.00        32
          2       1.00      1.00      1.00        52
          3       1.00      1.00      1.00        34
          4       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00       161

